<a href="https://colab.research.google.com/github/vachan-maker/Data-Science-Course/blob/main/18th_June.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy ndarray: A multidimensional array object

- Numpy can create n dimensional arrays


In [ ]:
import numpy as np
a = np.array([1,2,3,4,5,6]) #converting a list to array
a

A = np.zeros(3) #one dimensional array with 3 zeroes
b = np.ones(5)
A
b

array([1., 1., 1., 1., 1.])

In [ ]:
data1 = [6, 7, 5, '8',1,0] #list  can contain more than one data type
arr1 = np.array(data1) #array contains only the same data type
arr1

print()

array(['6', '7', '5', '8', '1', '0'], dtype='<U21')

In [ ]:
print('Dtype:', arr1.dtype)

Dtype: <U21


In [ ]:
data2 = [[1,2,3,4], [5,6,7,8], [9,10,11,20]] #three lists in a single list
arr2 = np.array(data2)
arr2
print('Dimensions', arr2.ndim)
#how many dimensions are there in this array
#shape will tell how many rows and columns


Dimensions 2


In [ ]:
np.zeros(10)
np.ones((3,6)) # 3 rows with 6 columns
np.ones((2,3,2) ) #three dimensional array
# First Dim:2
# Second Dim: 3
# Third Dim:2 entire thing is duplicated again


array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

## What is np.arange?

for creating an array with a sequence of numbers
- start: start value of the sequence
- stop: end value(excluded)
- step: the difference between each pair
- dtype : data type

default step size is 1

In [ ]:
s = np.arange(4,200,5)
s

array([  4,   9,  14,  19,  24,  29,  34,  39,  44,  49,  54,  59,  64,
        69,  74,  79,  84,  89,  94,  99, 104, 109, 114, 119, 124, 129,
       134, 139, 144, 149, 154, 159, 164, 169, 174, 179, 184, 189, 194,
       199])

In [ ]:
arr2 = np.arange(100)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [ ]:
arr4 = np.arange(100,150,.5,dtype=float)

# Linspace
np.linspace is another function in the numpy library that generates an array over a specified interval

In summary, use linspace when you know the number of points you want, and use arange when you know the step size.

In [ ]:
arr=np.linspace(1,40,5)
arr

array([ 1.  , 10.75, 20.5 , 30.25, 40.  ])

In [ ]:
numeric_strings = np.array(['1','2','5'], dtype=np.string_)
numeric_strings.astype(float)

#convert string to float

array([1., 2., 5.])

# Generate random integers


In [ ]:

i = np.random.rand()
i

0.4922300277290017

In [ ]:
j = np.random.rand(1,10)
j

array([[0.5839178 , 0.10539777, 0.46499464, 0.88959813, 0.61222493,
        0.81704399, 0.03703606, 0.73755634, 0.33668359, 0.18395931]])

In [ ]:
# to generate 5 random numbers
r_arr = np.random.rand(5)
r_arr

array([0.10119378, 0.06301686, 0.55093825, 0.90882695, 0.60336668])

In [ ]:
r_arr = np.random.randint(1,10,size = 5)
r_arr

array([5, 6, 4, 9, 2])

In [ ]:
#generate two dimensional random numbers
r_2d = np.random.randint(1, 10, size = (3,3))
r_2d

array([[5, 8, 1],
       [9, 5, 5],
       [4, 1, 3]])

Learn indexing and splicing of arrays